<?php
	$ext = ".svg";
	$width = 100;

	switch($this->getMethodCode()) {
		case "yuansfer_alipay":
			$ext = ".svg";
			$width = 165;
			break;
		case "yuansfer_unionpay":
			$ext = ".svg";
			$width = 89;
			break;
    	case "yuansfer_wechatpay":
			$ext = ".png";
			$width = 200;
			break;
	}
?>
<ul class="form-list yuansfer-securepays" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
	<img src="<?php echo $this->getSkinUrl( 'yuansfer/' . $this->getMethodCode() .'/logo_' . Mage::app()->getLocale()->getLocaleCode() . $ext); ?>" width="<?php echo $width ?>">
	<br/>
	<p><strong><?php echo $this->__('You will be taken to the payment website when you click Place Order');?></strong></p>
    </li>
</ul>
